''' Created on Tue jan 24 12:56 PM 2022

@author: Md. Nadim Sarwar

'''

# Classifying fake news with MultinomialNB Algorithm

# Importing Libraries

In [53]:
import numpy as np
import pandas as pd
import re
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

# Reading data

In [54]:
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')
test_label = pd.read_csv('test_label.csv')

train_data.reset_index(inplace=True) #indexing
test_data.reset_index(inplace=True)

In [32]:
train_data.head(10) #for chacking

index  id                                              title  \
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   
5      5   5  Jackie Mason: Hollywood Would Love Trump if He...   
6      6   6  Life: Life Of Luxury: Elton John’s 6 Favorite ...   
7      7   7  Benoît Hamon Wins French Socialist Party’s Pre...   
8      8   8  Excerpts From a Draft Script for Donald Trump’...   
9      9   9  A Back-Channel Plan for Ukraine and Russia, Co...   

                         author  \
0                 Darrell Lucus   
1               Daniel J. Flynn   
2            Consortiumnews.com   
3               Jessica Purkiss   
4                Howard Portnoy   
5               Daniel Nussbaum   
6                           NaN   
7               Alissa J. Rubin   
8                           NaN   
9  Megan Twohey and Scott Shane   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1  
5  In these trying times, Jackie Mason is the Voi...      0  
6  Ever wonder how Britain’s most iconic pop pian...      1  
7  PARIS  —   France chose an idealistic, traditi...      0  
8  Donald J. Trump is scheduled to make a highly ...      0  
9  A week before Michael T. Flynn resigned as nat...      0

In [33]:
test_data.head(10) #for chacking

index     id                                              title  \
0      0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1      1  20801  Russian warships ready to strike terrorists ne...   
2      2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3      3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4      4  20804                    Keiser Report: Meme Wars (E995)   
5      5  20805  Trump is USA's antique hero. Clinton will be n...   
6      6  20806  Pelosi Calls for FBI Investigation to Find Out...   
7      7  20807            Weekly Featured Profile – Randy Shannon   
8      8  20808  Urban Population Booms Will Make Climate Chang...   
9      9  20809                                                NaN   

                    author                                               text  
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...  
1                      NaN  Russian warships ready to strike terrorists ne...  
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...  
3            Daniel Victor  If at first you don’t succeed, try a different...  
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...  
5                      NaN  Trump is USA's antique hero. Clinton will be n...  
6                  Pam Key  Sunday on NBC’s “Meet the Press,” House Minori...  
7            Trevor Loudon  You are here: Home / *Articles of the Bound* /...  
8                      NaN  Urban Population Booms Will Make Climate Chang...  
9      cognitive dissident                         don't we have the receipt?

In [34]:
test_label.head(10) #for chacking

id  label
0  20800      0
1  20801      1
2  20802      0
3  20803      1
4  20804      1
5  20805      1
6  20806      1
7  20807      1
8  20808      0
9  20809      1

# Cleaning part

In [55]:
wn = WordNetLemmatizer()
lst_train_data = []
lst_test_data = []

for i in range(0, len(train_data)):
    text_1 = re.sub('[^a-zA-Z]', ' ', str(train_data['title'][i]))
    text_1 = text_1.lower()
    text_1 = text_1.split()
    text_1 = [wn.lemmatize(word_1) for word_1 in text_1 if not word_1 in stopwords.words('english')]
    text_1 = ' '.join(text_1)
    lst_train_data.append(text_1)
    
for i in range(0, len(test_data)):
    text_2 = re.sub('[^a-zA-Z]', ' ', str(test_data['title'][i]))
    text_2 = text_2.lower()
    text_2 = text_2.split()
    text_2 = [wn.lemmatize(word_2) for word_2 in text_2 if not word_2 in stopwords.words('english')]
    text_2 = ' '.join(text_2)
    lst_test_data.append(text_2)

In [56]:
lst_train_data[0] #for checking

'house dem aide even see comey letter jason chaffetz tweeted'

In [57]:
lst_test_data[0] #for checking

'specter trump loosens tongue purse string silicon valley new york time'

# Applying Bag_of_words

In [58]:
cv = CountVectorizer(max_features=5000,ngram_range=(1,3))

x_train_data = cv.fit_transform(lst_train_data).toarray()
x_test_data = cv.fit_transform(lst_test_data).toarray()

y_train_data = train_data['label']
y_test_data = test_label['label']

In [59]:
x_train_data #for checking

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [40]:
x_test_data #for checking

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [46]:
y_train_data #for checking

0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 20800, dtype: int64

In [47]:
y_test_data #for checking

0       0
1       1
2       0
3       1
4       1
       ..
5195    0
5196    1
5197    0
5198    1
5199    0
Name: label, Length: 5200, dtype: int64

# Using MultinomialNB Algorithm

In [60]:
classifier = MultinomialNB()
classifier.fit(x_train_data, y_train_data)

MultinomialNB()

# Accuracy and Confusion matrix

In [61]:
pred = classifier.predict(x_test_data)
acc = metrics.accuracy_score(y_test_data,pred)
cm = metrics.confusion_matrix(y_test_data, pred)
print('Accuracy = ',acc)
print(cm)

Accuracy =  0.6257692307692307
[[1194 1145]
 [ 801 2060]]
